//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_border2_H
#define METASPRITE_border2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define border2_TILE_ORIGIN 0
#define border2_TILE_W 8
#define border2_TILE_H 8
#define border2_WIDTH 80
#define border2_HEIGHT 64
#define border2_TILE_COUNT 9
#define border2_PALETTE_COUNT 8
#define border2_COLORS_PER_PALETTE 4
#define border2_TOTAL_COLORS 32
#define border2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(border2)

extern const palette_color_t border2_palettes[32];
extern const uint8_t border2_tiles[144];

extern const unsigned char border2_map[80];

#endif
