//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt9_H
#define METASPRITE_font_alt9_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt9_TILE_ORIGIN 0
#define font_alt9_TILE_W 8
#define font_alt9_TILE_H 8
#define font_alt9_WIDTH 32
#define font_alt9_HEIGHT 48
#define font_alt9_TILE_COUNT 20
#define font_alt9_PALETTE_COUNT 0
#define font_alt9_COLORS_PER_PALETTE 4
#define font_alt9_TOTAL_COLORS 0
#define font_alt9_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt9)

extern const palette_color_t font_alt9_palettes[0];
extern const uint8_t font_alt9_tiles[320];

extern const unsigned char font_alt9_map[24];

#endif
