//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font6_H
#define METASPRITE_font6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font6_TILE_ORIGIN 0
#define font6_TILE_W 8
#define font6_TILE_H 8
#define font6_WIDTH 32
#define font6_HEIGHT 48
#define font6_TILE_COUNT 21
#define font6_PALETTE_COUNT 1
#define font6_COLORS_PER_PALETTE 4
#define font6_TOTAL_COLORS 4
#define font6_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font6)

extern const palette_color_t font6_palettes[4];
extern const uint8_t font6_tiles[336];

extern const unsigned char font6_map[24];

#endif
