//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt1_H
#define METASPRITE_font_alt1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt1_TILE_ORIGIN 0
#define font_alt1_TILE_W 8
#define font_alt1_TILE_H 8
#define font_alt1_WIDTH 32
#define font_alt1_HEIGHT 48
#define font_alt1_TILE_COUNT 10
#define font_alt1_PALETTE_COUNT 0
#define font_alt1_COLORS_PER_PALETTE 4
#define font_alt1_TOTAL_COLORS 0
#define font_alt1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt1)

extern const palette_color_t font_alt1_palettes[0];
extern const uint8_t font_alt1_tiles[160];

extern const unsigned char font_alt1_map[24];

#endif
