//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt5_H
#define METASPRITE_font_alt5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt5_TILE_ORIGIN 0
#define font_alt5_TILE_W 8
#define font_alt5_TILE_H 8
#define font_alt5_WIDTH 32
#define font_alt5_HEIGHT 48
#define font_alt5_TILE_COUNT 22
#define font_alt5_PALETTE_COUNT 0
#define font_alt5_COLORS_PER_PALETTE 4
#define font_alt5_TOTAL_COLORS 0
#define font_alt5_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt5)

extern const palette_color_t font_alt5_palettes[0];
extern const uint8_t font_alt5_tiles[352];

extern const unsigned char font_alt5_map[24];

#endif
