//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt4_H
#define METASPRITE_font_alt4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt4_TILE_ORIGIN 0
#define font_alt4_TILE_W 8
#define font_alt4_TILE_H 8
#define font_alt4_WIDTH 32
#define font_alt4_HEIGHT 48
#define font_alt4_TILE_COUNT 16
#define font_alt4_PALETTE_COUNT 0
#define font_alt4_COLORS_PER_PALETTE 4
#define font_alt4_TOTAL_COLORS 0
#define font_alt4_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt4)

extern const palette_color_t font_alt4_palettes[0];
extern const uint8_t font_alt4_tiles[256];

extern const unsigned char font_alt4_map[24];

#endif
