//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt8_H
#define METASPRITE_font_alt8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt8_TILE_ORIGIN 0
#define font_alt8_TILE_W 8
#define font_alt8_TILE_H 8
#define font_alt8_WIDTH 32
#define font_alt8_HEIGHT 48
#define font_alt8_TILE_COUNT 19
#define font_alt8_PALETTE_COUNT 0
#define font_alt8_COLORS_PER_PALETTE 4
#define font_alt8_TOTAL_COLORS 0
#define font_alt8_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt8)

extern const palette_color_t font_alt8_palettes[0];
extern const uint8_t font_alt8_tiles[304];

extern const unsigned char font_alt8_map[24];

#endif
