//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt6_H
#define METASPRITE_font_alt6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt6_TILE_ORIGIN 0
#define font_alt6_TILE_W 8
#define font_alt6_TILE_H 8
#define font_alt6_WIDTH 32
#define font_alt6_HEIGHT 48
#define font_alt6_TILE_COUNT 21
#define font_alt6_PALETTE_COUNT 0
#define font_alt6_COLORS_PER_PALETTE 4
#define font_alt6_TOTAL_COLORS 0
#define font_alt6_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt6)

extern const palette_color_t font_alt6_palettes[0];
extern const uint8_t font_alt6_tiles[336];

extern const unsigned char font_alt6_map[24];

#endif
