//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font9_H
#define METASPRITE_font9_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font9_TILE_ORIGIN 0
#define font9_TILE_W 8
#define font9_TILE_H 8
#define font9_WIDTH 32
#define font9_HEIGHT 48
#define font9_TILE_COUNT 20
#define font9_PALETTE_COUNT 1
#define font9_COLORS_PER_PALETTE 4
#define font9_TOTAL_COLORS 4
#define font9_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font9)

extern const palette_color_t font9_palettes[4];
extern const uint8_t font9_tiles[320];

extern const unsigned char font9_map[24];

#endif
