//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font9_v_H
#define METASPRITE_font9_v_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font9_v_TILE_ORIGIN 0
#define font9_v_TILE_W 8
#define font9_v_TILE_H 8
#define font9_v_WIDTH 48
#define font9_v_HEIGHT 32
#define font9_v_TILE_COUNT 20
#define font9_v_PALETTE_COUNT 1
#define font9_v_COLORS_PER_PALETTE 4
#define font9_v_TOTAL_COLORS 4
#define font9_v_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font9_v)

extern const palette_color_t font9_v_palettes[4];
extern const uint8_t font9_v_tiles[320];

extern const unsigned char font9_v_map[24];

#endif
