//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font4_H
#define METASPRITE_font4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font4_TILE_ORIGIN 0
#define font4_TILE_W 8
#define font4_TILE_H 8
#define font4_WIDTH 32
#define font4_HEIGHT 48
#define font4_TILE_COUNT 16
#define font4_PALETTE_COUNT 1
#define font4_COLORS_PER_PALETTE 4
#define font4_TOTAL_COLORS 4
#define font4_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font4)

extern const palette_color_t font4_palettes[4];
extern const uint8_t font4_tiles[256];

extern const unsigned char font4_map[24];

#endif
