//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt2_H
#define METASPRITE_font_alt2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt2_TILE_ORIGIN 0
#define font_alt2_TILE_W 8
#define font_alt2_TILE_H 8
#define font_alt2_WIDTH 32
#define font_alt2_HEIGHT 48
#define font_alt2_TILE_COUNT 17
#define font_alt2_PALETTE_COUNT 0
#define font_alt2_COLORS_PER_PALETTE 4
#define font_alt2_TOTAL_COLORS 0
#define font_alt2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt2)

extern const palette_color_t font_alt2_palettes[0];
extern const uint8_t font_alt2_tiles[272];

extern const unsigned char font_alt2_map[24];

#endif
