//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font1_H
#define METASPRITE_font1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font1_TILE_ORIGIN 0
#define font1_TILE_W 8
#define font1_TILE_H 8
#define font1_WIDTH 32
#define font1_HEIGHT 48
#define font1_TILE_COUNT 10
#define font1_PALETTE_COUNT 1
#define font1_COLORS_PER_PALETTE 4
#define font1_TOTAL_COLORS 4
#define font1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font1)

extern const palette_color_t font1_palettes[4];
extern const uint8_t font1_tiles[160];

extern const unsigned char font1_map[24];

#endif
