//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font3_H
#define METASPRITE_font3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font3_TILE_ORIGIN 0
#define font3_TILE_W 8
#define font3_TILE_H 8
#define font3_WIDTH 32
#define font3_HEIGHT 48
#define font3_TILE_COUNT 15
#define font3_PALETTE_COUNT 1
#define font3_COLORS_PER_PALETTE 4
#define font3_TOTAL_COLORS 4
#define font3_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font3)

extern const palette_color_t font3_palettes[4];
extern const uint8_t font3_tiles[240];

extern const unsigned char font3_map[24];

#endif
