//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt11_H
#define METASPRITE_font_alt11_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt11_TILE_ORIGIN 0
#define font_alt11_TILE_W 8
#define font_alt11_TILE_H 8
#define font_alt11_WIDTH 32
#define font_alt11_HEIGHT 48
#define font_alt11_TILE_COUNT 16
#define font_alt11_PALETTE_COUNT 0
#define font_alt11_COLORS_PER_PALETTE 4
#define font_alt11_TOTAL_COLORS 0
#define font_alt11_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt11)

extern const palette_color_t font_alt11_palettes[0];
extern const uint8_t font_alt11_tiles[256];

extern const unsigned char font_alt11_map[24];

#endif
