//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font5_H
#define METASPRITE_font5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font5_TILE_ORIGIN 0
#define font5_TILE_W 8
#define font5_TILE_H 8
#define font5_WIDTH 32
#define font5_HEIGHT 48
#define font5_TILE_COUNT 22
#define font5_PALETTE_COUNT 1
#define font5_COLORS_PER_PALETTE 4
#define font5_TOTAL_COLORS 4
#define font5_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font5)

extern const palette_color_t font5_palettes[4];
extern const uint8_t font5_tiles[352];

extern const unsigned char font5_map[24];

#endif
