//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font10_H
#define METASPRITE_font10_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font10_TILE_ORIGIN 0
#define font10_TILE_W 8
#define font10_TILE_H 8
#define font10_WIDTH 32
#define font10_HEIGHT 48
#define font10_TILE_COUNT 16
#define font10_PALETTE_COUNT 1
#define font10_COLORS_PER_PALETTE 4
#define font10_TOTAL_COLORS 4
#define font10_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font10)

extern const palette_color_t font10_palettes[4];
extern const uint8_t font10_tiles[256];

extern const unsigned char font10_map[24];

#endif
