//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt3_H
#define METASPRITE_font_alt3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt3_TILE_ORIGIN 0
#define font_alt3_TILE_W 8
#define font_alt3_TILE_H 8
#define font_alt3_WIDTH 32
#define font_alt3_HEIGHT 48
#define font_alt3_TILE_COUNT 15
#define font_alt3_PALETTE_COUNT 0
#define font_alt3_COLORS_PER_PALETTE 4
#define font_alt3_TOTAL_COLORS 0
#define font_alt3_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt3)

extern const palette_color_t font_alt3_palettes[0];
extern const uint8_t font_alt3_tiles[240];

extern const unsigned char font_alt3_map[24];

#endif
