//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font0_H
#define METASPRITE_font0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font0_TILE_ORIGIN 0
#define font0_TILE_W 8
#define font0_TILE_H 8
#define font0_WIDTH 32
#define font0_HEIGHT 48
#define font0_TILE_COUNT 21
#define font0_PALETTE_COUNT 1
#define font0_COLORS_PER_PALETTE 4
#define font0_TOTAL_COLORS 4
#define font0_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font0)

extern const palette_color_t font0_palettes[4];
extern const uint8_t font0_tiles[336];

extern const unsigned char font0_map[24];

#endif
