//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font3_v_H
#define METASPRITE_font3_v_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font3_v_TILE_ORIGIN 0
#define font3_v_TILE_W 8
#define font3_v_TILE_H 8
#define font3_v_WIDTH 48
#define font3_v_HEIGHT 32
#define font3_v_TILE_COUNT 15
#define font3_v_PALETTE_COUNT 1
#define font3_v_COLORS_PER_PALETTE 4
#define font3_v_TOTAL_COLORS 4
#define font3_v_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font3_v)

extern const palette_color_t font3_v_palettes[4];
extern const uint8_t font3_v_tiles[240];

extern const unsigned char font3_v_map[24];

#endif
