//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font11_v_H
#define METASPRITE_font11_v_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font11_v_TILE_ORIGIN 0
#define font11_v_TILE_W 8
#define font11_v_TILE_H 8
#define font11_v_WIDTH 48
#define font11_v_HEIGHT 32
#define font11_v_TILE_COUNT 16
#define font11_v_PALETTE_COUNT 1
#define font11_v_COLORS_PER_PALETTE 4
#define font11_v_TOTAL_COLORS 4
#define font11_v_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font11_v)

extern const palette_color_t font11_v_palettes[4];
extern const uint8_t font11_v_tiles[256];

extern const unsigned char font11_v_map[24];

#endif
