//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt10_H
#define METASPRITE_font_alt10_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt10_TILE_ORIGIN 0
#define font_alt10_TILE_W 8
#define font_alt10_TILE_H 8
#define font_alt10_WIDTH 32
#define font_alt10_HEIGHT 48
#define font_alt10_TILE_COUNT 16
#define font_alt10_PALETTE_COUNT 0
#define font_alt10_COLORS_PER_PALETTE 4
#define font_alt10_TOTAL_COLORS 0
#define font_alt10_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt10)

extern const palette_color_t font_alt10_palettes[0];
extern const uint8_t font_alt10_tiles[256];

extern const unsigned char font_alt10_map[24];

#endif
