//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font11_H
#define METASPRITE_font11_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font11_TILE_ORIGIN 0
#define font11_TILE_W 8
#define font11_TILE_H 8
#define font11_WIDTH 32
#define font11_HEIGHT 48
#define font11_TILE_COUNT 16
#define font11_PALETTE_COUNT 1
#define font11_COLORS_PER_PALETTE 4
#define font11_TOTAL_COLORS 4
#define font11_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font11)

extern const palette_color_t font11_palettes[4];
extern const uint8_t font11_tiles[256];

extern const unsigned char font11_map[24];

#endif
