//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font7_H
#define METASPRITE_font7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font7_TILE_ORIGIN 0
#define font7_TILE_W 8
#define font7_TILE_H 8
#define font7_WIDTH 32
#define font7_HEIGHT 48
#define font7_TILE_COUNT 14
#define font7_PALETTE_COUNT 1
#define font7_COLORS_PER_PALETTE 4
#define font7_TOTAL_COLORS 4
#define font7_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font7)

extern const palette_color_t font7_palettes[4];
extern const uint8_t font7_tiles[224];

extern const unsigned char font7_map[24];

#endif
