//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt0_H
#define METASPRITE_font_alt0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt0_TILE_ORIGIN 0
#define font_alt0_TILE_W 8
#define font_alt0_TILE_H 8
#define font_alt0_WIDTH 32
#define font_alt0_HEIGHT 48
#define font_alt0_TILE_COUNT 21
#define font_alt0_PALETTE_COUNT 0
#define font_alt0_COLORS_PER_PALETTE 4
#define font_alt0_TOTAL_COLORS 0
#define font_alt0_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt0)

extern const palette_color_t font_alt0_palettes[0];
extern const uint8_t font_alt0_tiles[336];

extern const unsigned char font_alt0_map[24];

#endif
