//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font2_H
#define METASPRITE_font2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font2_TILE_ORIGIN 0
#define font2_TILE_W 8
#define font2_TILE_H 8
#define font2_WIDTH 32
#define font2_HEIGHT 48
#define font2_TILE_COUNT 17
#define font2_PALETTE_COUNT 1
#define font2_COLORS_PER_PALETTE 4
#define font2_TOTAL_COLORS 4
#define font2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font2)

extern const palette_color_t font2_palettes[4];
extern const uint8_t font2_tiles[272];

extern const unsigned char font2_map[24];

#endif
