//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font8_H
#define METASPRITE_font8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font8_TILE_ORIGIN 0
#define font8_TILE_W 8
#define font8_TILE_H 8
#define font8_WIDTH 32
#define font8_HEIGHT 48
#define font8_TILE_COUNT 19
#define font8_PALETTE_COUNT 1
#define font8_COLORS_PER_PALETTE 4
#define font8_TOTAL_COLORS 4
#define font8_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font8)

extern const palette_color_t font8_palettes[4];
extern const uint8_t font8_tiles[304];

extern const unsigned char font8_map[24];

#endif
