//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt7_H
#define METASPRITE_font_alt7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt7_TILE_ORIGIN 0
#define font_alt7_TILE_W 8
#define font_alt7_TILE_H 8
#define font_alt7_WIDTH 32
#define font_alt7_HEIGHT 48
#define font_alt7_TILE_COUNT 14
#define font_alt7_PALETTE_COUNT 0
#define font_alt7_COLORS_PER_PALETTE 4
#define font_alt7_TOTAL_COLORS 0
#define font_alt7_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt7)

extern const palette_color_t font_alt7_palettes[0];
extern const uint8_t font_alt7_tiles[224];

extern const unsigned char font_alt7_map[24];

#endif
