//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_alt7_v_H
#define METASPRITE_font_alt7_v_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_alt7_v_TILE_ORIGIN 0
#define font_alt7_v_TILE_W 8
#define font_alt7_v_TILE_H 8
#define font_alt7_v_WIDTH 48
#define font_alt7_v_HEIGHT 32
#define font_alt7_v_TILE_COUNT 14
#define font_alt7_v_PALETTE_COUNT 0
#define font_alt7_v_COLORS_PER_PALETTE 4
#define font_alt7_v_TOTAL_COLORS 0
#define font_alt7_v_MAP_ATTRIBUTES 0

BANKREF_EXTERN(font_alt7_v)

extern const palette_color_t font_alt7_v_palettes[0];
extern const uint8_t font_alt7_v_tiles[224];

extern const unsigned char font_alt7_v_map[24];

#endif
