//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_watchface_H
#define METASPRITE_watchface_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define watchface_TILE_ORIGIN 0
#define watchface_TILE_W 8
#define watchface_TILE_H 8
#define watchface_WIDTH 256
#define watchface_HEIGHT 24
#define watchface_TILE_COUNT 94
#define watchface_PALETTE_COUNT 1
#define watchface_COLORS_PER_PALETTE 4
#define watchface_TOTAL_COLORS 4
#define watchface_PIVOT_X 128
#define watchface_PIVOT_Y 12
#define watchface_PIVOT_W 256
#define watchface_PIVOT_H 24

BANKREF_EXTERN(watchface)

extern const palette_color_t watchface_palettes[4];
extern const uint8_t watchface_tiles[1504];

extern const metasprite_t* const watchface_metasprites[1];

#endif
